poll/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home, name='home'),
    path('polls/', include('polls.urls',namespace='polls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('list/', views.polls_list, name='polls_list'),
    path('<int:poll_id>/', views.polls_detail, name='detail'),
    path('<int:poll_id>/poll_vote/', views.poll_vote, name='poll_vote'),
]

polls/models.py
from django.db import models


class poll(models.Model):
    text = models.CharField(max_length=255)
    pub_date = models.DateField()

    def __str__(self):
        return self.text


class choice(models.Model):
    question = models.ForeignKey(poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "{} - {}".format(self.question.text[:25], self.choice_text[:25])

poll/views.py
from django.shortcuts import render


def home(request):
    context = {}
    return render(request, 'home.html', context)

polls/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import poll, choice
from django.shortcuts import get_object_or_404


def polls_list(request):
    polls = poll.objects.all()
    context = {'polls': polls}
    return render(request, 'polls/polls_list.html', context)


def polls_detail(request, poll_id):
    polls = get_object_or_404(poll, id=poll_id)
    context = {'poll': polls}
    return render(request, 'polls/polls_details.html', context)


def poll_vote(request, poll_id):
    choice_id = request.POST.get('choice')
    p = get_object_or_404(poll, id=poll_id)
    if choice_id:
        c = choice.objects.get(id=choice_id)
        c.votes += 1
        c.save()
    else:
        messages.error(request, 'No choice found')
    return render(request, 'polls/polls_results.html', {'poll': p})

polls/templates/polls/polls_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Poll | {{ poll.text | capfirst }} {% endblock %}

{% block content %}
    <br>
    <br>
    <center>
    <form action="{% url 'polls:poll_vote' poll.id %}" method="post">
    {% csrf_token %}
    <div class="col-md-5">
    <div class="card">
        <div class="card-body">
            <!-- Title -->
            <h4 class="card-title">{{ poll.text | title}}</h4>
            <!-- Text -->
            <p class="card-text">
                <div class="row">
                    <div class="col-lg-4"></div>
                        {% for choice in poll.choice_set.all %}
                            <div class="col-sm-2">
                                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                            </div>
                        {% endfor %}
                    </div>
            </p>

        <input type="submit" value="Vote" class="btn btn-indigo btn-md btn-rounded">
        </div>
    </div>
    </div>
    </form>
    </center>
{#    </div>#}
{#    <center><h1>{{ poll.text | title}}</h1>#}
{#    <form action="" method="post">#}
{#    {% csrf_token %}#}
{#    <br>#}
{#    <div class="row">#}
{#        <div class="col-lg-4"></div>#}
{#        {% for choice in poll.choice_set.all %}#}
{#        <div class="col-sm-2">#}
{#            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">#}
{#            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>#}
{#        </div>#}
{#        {% endfor %}#}
{#    </div>#}
{##}
{#    <input type="submit" value="Vote" class="btn btn-indigo btn-md">#}
{#    </form>#}
{#    </center>#}
{% endblock %}

polls/templates/polls/polls_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Poll | Poll list{% endblock %}
{% block custom_css %}<link rel="stylesheet" type="text/css" href="{% static 'css/list_style.css' %}">{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <center><h1 class="title-font">WELCOME TO POLL LIST</h1></center>
        <hr/>
        <ul class="list-group">
        {% for poll in polls %}
            <li>
            <span class="list-group-item">
                <div class="card">

                    <!-- Card content -->
                    <div class="card-body">
                        <div class="row">
                        <div class="col-md-8">
                        <!-- Title -->
                        <h4 class="card-title">{{ poll | capfirst }}

                        </h4>
                        </div>
                            <div class="col-md-2">
                                {% for choice in poll.choice_set.all %}
                                    <h5><span class="badge badge-default badge-pill">{{ choice.choice_text }}: {{ choice.votes }}</span></h5>
                                {% endfor %}
                            </div>
                        <!-- Button -->
                        <div class="col-md-2">
                        <a href="{% url 'polls:detail' poll.id %}" class="btn btn-indigo btn-rounded">View</a>
                            </div>
                        </div>
                    </div>

                </div>
{#            <span class="list-group-item"><a href="{% url 'polls:detail' poll.id %}"> {{ poll | capfirst}} </a>#}
{#            {% for choice in poll.choice_set.all %}#}
{#                <span class="badge badge-default badge-pill">{{ choice.choice_text }}</span>#}
{#            {% endfor %}#}
            </span>
            </li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

polls/templates/polls/polls_results.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Poll | {{ poll.text | capfirst }} {% endblock %}

{% block content %}
    <br>
    <br>
    <center>
    <div class="col-md-5">
    <div class="card">
        <div class="card-body">
            <!-- Title -->
            <h4 class="card-title">{{ poll.text | title}}</h4>
            <!-- Text -->
            <p class="card-text">
                <div class="row">
                    <div class="col-lg-4"></div>
                        {% for choice in poll.choice_set.all %}
                            <div class="col-sm-2">

                                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }} - {{ choice.votes }}</label>
                            </div>
                        {% endfor %}
                    </div>
            </p>

        </div>
    </div>
    </div>
    </center>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="position: fixed; bottom: 5px; left: 2%; width: 96%;">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Poll | Base{% endblock %}</title>

    <link rel="shortcut icon" type="img/jpg" href="{% static 'img/favicon.jpg' %}"/>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">#}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">

    {% block custom_css %} {% endblock %}

</head>
<body>
    {% include 'includes/navbar.html' %}
    {% block content %}
    <h1>This header tag will be overwritten by any child template.</h1>
    {% endblock %}

    <!-- JQuery -->
    <script type="text/javascript" src="{% static  'js/jquery-3.3.1.min.js'%}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static  'js/popper.min.js'%}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static  'js/bootstrap.min.js'%}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static  'js/mdb.min.js'%}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Poll | Home{% endblock %}
{% block custom_css %}<link rel="stylesheet" type="text/css" href="{% static 'css/home_styles.css' %}">{% endblock %}
{% block content %}
<div class="container">
    <div class="bg-img"> </div>
<div class="row">
    <div class="col">
        <div id="home-content">
            <h1>Poll - Get Started!</h1>
            <h3>Your Voice Matters!</h3>
            <hr>
            <a href="{% url 'polls:polls_list' %}"><button type="button" class="btn blue-gradient btn-rounded waves-effect"><strong>Get Started!</strong></button></a>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark indigo">
      <a class="navbar-brand" href="{% url 'home' %}">POLL!!</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:polls_list' %}">Poll</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="/admin">Admin</a>
            </li>
        </ul>
      </div>
    </nav>